travis:
  secure:
    BINSTAR_TOKEN: jnIfFtbsHmP1AERlaQ4fLHc76xL1Ipj3A7GA5dF8voOdGFezNXJaU6UJaH/1vZYc3ogjCsl5uXHAtZ4qBXFTgHU+lOoxRgE5qp14q0qn34gc5Ec22GPBOvtrbUcuYbV2/1k0Hw0XfuatQsEiEDWhsiyur3IiNrXFGrOtGSSJt8S1dQbT+I7A5RnjaCOAZLqutgXVuDkFLM1RhlS5RwlxAdalL4cnKt9R8SiYyLItO90we6tQeigdUCMD/65IH8Mw4IbgG60W55Sas/SsZWk2jWSY2Ju+4+olwmsOqsHV53p+Z2pN9pwb3UqJWZHxnV6ZjvVoxU4m6c28aUGuUEPzT7PA0oZQNdQnwYW1EIomrw98ks6pRaoHOSg/VPoVExRaJOIwU1FQi4t3DNq1yXIpx7dajw4dH1kWXWcP07oXwGrKLWqPajhJnhDVn0AMiHQeGSKBhIPsRFPRZSXh+mq76oMUoSbu9UHFnKpaBWyCdfPf4V5t5KS3tZQhvMvrVfVgnMKV/gJ8XmVjUgP+4EXkR8sGdeimzcFfg5HhliQCmnlYbbEkDjR0MEW1Twyct2LjFAgmbYmOFeK1zjdR8nL79jehkOp0PQbiVz+JZIwD66ro+AfPf05N7hX4HTBbIyHQ/LFB/OM3IOY659ef39ngn8A1IcOCFkb4An+KteGNxYU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
